### ISSUE TITLE
Rename to SpikingNeuralNetworks.jl and register in General

### ISSUE THREAD

**Issue by jpsamaroo** [AStupidBear/SpikingNeuralNetworks.jl#4]
As recommended in the pkg-usage channel on Slack, this package should be renamed to something like SpikingNeuralNetworks.jl before registering it in the General registry.

**Comment by AStupidBear** [comment]
Thanks for your nice fix. I'm releasing a bunch of packages recently and planning to revive this package and write some documentations. Could you please wait for one day and collaborate here?

**Comment by jpsamaroo** [comment]
Thanks for responding, and for merging #1! I'll move my work over here then.

I cancelled the open General registration PR for my own repo, I'll post a PR momentarily to fix some compat upper-bounds in the Project.toml and then we can register this package once that is merged and JuliaRegistrator is installed on this repo (which I think is something you need to do).

**Comment by AStupidBear** [comment]
I have installed JuliaRegistrator in my account and registered some other packages. Is that sufficient?

**Comment by jpsamaroo** [comment]
#5 is needed first

**Comment by jpsamaroo** [comment]
Ok, we can go ahead and register now. I think you can comment "@JuliaRegistrator register()" (without quotes) on the latest commit to initiate the registration.

**Comment by jpsamaroo** [comment]
Oh, apparently I could do it :smile: @AStupidBear I would also recommend installing Julia TagBot (as linked in the above comment).

**Comment by AStupidBear** [comment]
@jpsamaroo Julia TagBot is already installed.

**Comment by jpsamaroo** [comment]
Done!
